### ISSUE TITLE
Properly documents the :echo payload

### ISSUE THREAD

**Issue by plexus** [cgrand/unrepl#6]
The doc says this is what `:echo` looks like, 

```
[:echo {:file "" :start-line N :end-line N :start-column N :end-column N :offset N :len N} 1]
```

but in the examples (and what I'm also seeing) it looks like

```
[:echo {:from [1 1], :to [2 1]} 1]
```

**Comment by cgrand** [comment]
I'd like to know: isn't offset+len easier? Otherwise the spec should match the impl.

**Comment by cgrand** [comment]
When one sends for eval from a text editor, I expects a `:set-source` command to be invoked right before (so that errors & debug source info are correct). In this case having `:echo` replying in lines and columns make sense.
However from a repl buffer it makes less sense and offset + length may be a better match.
However due to the layered IO infrastructure, the server (in JS or Java) can't count the raw chars received, it can only count them after the "line delimiters conversion". So it means that the client must count chars in the same fashion for offsets to not drift.

**Comment by plexus** [comment]
Ok, that sounds reasonable, it just needs to be documented properly. I mainly opened this issue because I had no idea of the semantics of `:from [1 1]`. offset+length makes sense.
